-- TABLES
CREATE TABLE FOLDER (
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    VERSION_ID BIGINT NOT NULL
);

CREATE TABLE ITEM (
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    VERSION_ID BIGINT NOT NULL,
    FOLDER_ID BIGINT NOT NULL REFERENCES FOLDER(ID)
);

CREATE TABLE PROPERTY (
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    VERSION_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL REFERENCES ITEM(ID)
);

CREATE TABLE LABEL (
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY
);

CREATE TABLE ITEM_LABEL (
    ITEM_ID BIGINT NOT NULL REFERENCES ITEM(ID),
    LABEL_ID BIGINT NOT NULL REFERENCES LABEL(ID),
    UNIQUE(ITEM_ID, LABEL_ID)

);

-- INDICES
CREATE INDEX ITEM_FOLDER_ID ON ITEM(FOLDER_ID);
CREATE INDEX PROPERTY_ITEM_ID ON PROPERTY(ITEM_ID);
CREATE INDEX ITEM_LABEL_ITEM_ID ON ITEM_LABEL(ITEM_ID);
CREATE INDEX ITEM_LABEL_LABEL_ID ON ITEM_LABEL(LABEL_ID);